class API:
    ENDPOINT = "https://api.openweathermap.org/data/2.5/weather"


class Filter:
    WEATHER = ("weather", "main", "visibility", "wind", "clouds", "rain", "snow")


class Unit:
    STANDARD = "standard"
    METRIC = "metric"
    IMPERIAL = "imperial"


class Language:
    AFRIKAANS = "af"
    ALBANIAN = "al"
    ARABIC = "ar"
    AZERBAIJANI = "az"
    BULGARIAN = "bg"
    CATALAN = "ca"
    CZECH = "cz"
    DANISH = "da"
    GERMAN = "ge"
    GREEK = "el"
    ENGLISH = "en"
    BASQUE = "eu"
    PERSIAN_FARSI = "fa"
    FINNISH = "fi"
    FRENCH = "fr"
    GALICIAN = "gl"
    HEBREW = "he"
    HINDI = "hi"
    CROATIAN = "hr"
    HUNGARIAN = "hu"
    INDONESIAN = "id"
    ITALIAN = "it"
    JAPANESE = "ja"
    KOREAN = "kr"
    LATVIAN = "la"
    LITHUANIAN = "lt"
    MACEDONIAN = "mk"
    NORWEGIAN = "no"
    DUTCH = "nl"
    POLISH = "pl"
    PORTUGUESE = "pt"
    PORTUGUESE_BRASIL = "pt_br"
    ROMANIAN = "ro"
    RUSSIAN = "ru"
    SWEDISH = "se"
    SLOVAK = "sk"
    SLOVENIAN = "sl"
    SPANISH = "es"
    SERBIAN = "sr"
    THAI = "th"
    TURKISH = "tr"
    UKRAINIAN = "ua"
    VIETNAMESE = "vi"
    CHINESE_SIMPLIFIED = "zh_cn"
    CHINESE_TRADITIONAL = "zh_tw"
    ZULU = "zu"